# Generated by Django 4.1.6 on 2023-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('destination', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('number_of_days', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('holiday_type', models.CharField(max_length=20)),
            ],
        ),
    ]
